---
# Source: helm-example/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tekton-demo-helm-example
  labels:
    helm.sh/chart: helm-example-0.1.0
    app.kubernetes.io/name: helm-example
    app.kubernetes.io/instance: tekton-demo
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helm-example
    app.kubernetes.io/instance: tekton-demo
---
# Source: helm-example/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-demo-helm-example
  labels:
    helm.sh/chart: helm-example-0.1.0
    app.kubernetes.io/name: helm-example
    app.kubernetes.io/instance: tekton-demo
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-example
      app.kubernetes.io/instance: tekton-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helm-example
        app.kubernetes.io/instance: tekton-demo
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: helm-example
          securityContext:
            {}
          image: "443247825008.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd:29eaf3517a129e35d11fb87bc08642e5b30cac1b"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: helm-example/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "tekton-demo-helm-example-test-connection"
  labels:

    helm.sh/chart: helm-example-0.1.0
    app.kubernetes.io/name: helm-example
    app.kubernetes.io/instance: tekton-demo
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['tekton-demo-helm-example:80']
  restartPolicy: Never
